# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Garblemasher
email: justin@garblemasher.com
description: > # this means to ignore newlines until "baseurl:"
  My name's Justin. I'm a web developer and entreprenuer, passionate about
  changing the world. I'm a Mozilla QA Intern, and am part of OU's Class of
  2020, majoring in Management Information Systems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://garblemasher.com" # the base hostname & protocol for your site
twitter_username: PottsJustin
github_username:  justinpotts

# Build settings
markdown: kramdown
